### ISSUE TITLE
Release 1.0.5 version

### ISSUE THREAD

**Issue by EugeneTorap** [googleapis/python-db-dtypes-pandas#161]
#155 (Removes upper bound for pyarrow) is already merged.
Can we release a new version of `db-dtypes`?

**Comment by EugeneTorap** [comment]
@tswast @parthea @chalmerlowe Can we do it?

**Comment by tswast** [comment]
Unfortunately the bot didn't pick #155 up due to the "chore" prefix. See: https://github.com/googleapis/release-please#release-please-bot-does-not-create-a-release-pr-why

I think our best option would be to send an empty PR detailing #155 as a `deps: ` prefix with `git commit --allow-empty -m "deps: remove upper bound on pyarrow version"`

@EugeneTorap Would you mind sending one if I forget?

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/python-db-dtypes-pandas/pull/163
