### ISSUE TITLE
PR to pandas

### ISSUE THREAD

**Issue by tswast** [googleapis/python-db-dtypes-pandas#30]
pandas devs are open to an experimental date/time dtype.

We'd still keep this package around to backport the types to older pandas.

**Comment by jorisvandenbossche** [comment]
For

**Comment by jorisvandenbossche** [comment]
For `date`, the most relevant issue discussing this on the pandas side is https://github.com/pandas-dev/pandas/issues/32473

Now, I think there are still some aspects to discuss / decide upon on how we would like to approach the actual storage. For example, the advantage of what you are doing (using a datetime64 with midnight at zero) also has advantages versus storing the number of days since epoch (the conversion date <-> timestamp becomes much cheaper).

**Comment by chalmerlowe** [comment]
Closing. Looking to deprecate this library at some point in the future by relying upon existing datatypes in pandas and python.
